# Generated by Django 4.1.5 on 2023-01-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_created_at_profile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
