# Generated by Django 4.1.5 on 2023-01-21 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_vehicle_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclestation',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vehiclestation'),
        ),
    ]
