# Generated by Django 4.1.5 on 2023-01-21 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_vehiclehistory_vehicle_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclehistory',
            name='vehicle_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.vehiclestation'),
        ),
    ]
